//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beverage
    {
        public string id { get; set; }
        public string name { get; set; }
        public string pack { get; set; }
        public decimal price { get; set; }
        public bool active { get; set; }

        //Get the info from the beverage into one string
        public override string ToString()
        {
            return "Id: " + id + Environment.NewLine + "Name: " + name.Trim() + Environment.NewLine + "Pack: " + pack + Environment.NewLine + "Price: " + price + Environment.NewLine;
        }
    }
}
